### PR TITLE
Add "Factory" object with sensible defaults

### PR DESCRIPTION
**Pull request by guysv**
So, using https://github.com/libp2p/js-libp2p/pull/363, I wrote a "factory" class for webrtc-star which handles the integration into libp2p nodes, and populates some of the WebRTCStar options with sensible defaults.

### CODE REVIEW

**Comment by guysv** [comment]
I would also comment that I believe that feat/use-interface-data-exchange belongs to a new transport, ideas for names?

**Comment by guysv** [comment]
> I would also comment that I believe that feat/use-interface-data-exchange belongs to a new transport, ideas for a new name?
I suspect "libp2p-webrtc" will be sufficient

**Comment by vasco-santos** [comment]
Closing this as this is not relevant anymore with the latest release. 

Thanks for working on this @guysv

**Comment by vasco-santos** [comment]
Closing this as this repo was completely refactored. Thanks for trying to land this @guysv

**Pull request closed without merging**
