### PR TITLE
fix: do not assign read-only error.message

### PR DESCRIPTION
**Pull request by tabcat**
fixes assigning read only property in https://github.com/libp2p/js-libp2p-webrtc-star/issues/251

### CODE REVIEW

**Comment by tabcat** [comment]
If you want to keep the message the same I can make that change and log that instead of just the error.

**Review by vasco-santos — CHANGES_REQUESTED** [review]
Thanks for the PR and sorry for the delay to provide you an answer.

This seems good, but I would prefer to log the older message as well as it provides the host and port information that might be handy for debug.

**Comment by vasco-santos** [comment]
Hey @tabcat let me know if I should add a commit to add the older message

**Review by vasco-santos — CHANGES_REQUESTED** [review]

**Review by vasco-santos — APPROVED** [review]

**Comment by tabcat** [comment]
I missed your message from 8 days ago! Apologies and thanks for making the commit.

**Comment by tabcat** [comment]
Unfortunately we have not fixed the problem. My change has introduced a very similar problem to what it was supposed to fix.

Screenshot from 2020-10-18 22-48-49
Screenshot from 2020-10-18 22-49-10

Maybe explicitly make err into an Error? I really wish I would have tested now :sweat_smile:

**Comment by tabcat** [comment]
looks like this is already fixed in future version

**Pull request merged**
