### PR TITLE
feat: add instrumentation to sig server

### PR DESCRIPTION
**Pull request by diasdavid**

### CODE REVIEW

**Comment by diasdavid** [comment]
Does this -- https://github.com/roylines/node-epimetheus#instrumentation -- satisfy your requests, @lgierth ? :)

**Comment by VictorBjelkholm** [comment]
Would be wonderful to be able to get metrics about how many peers have ever been online and are currently online as well. Might want to add as a task for the future though.

**Comment by lgierth** [comment]
> how many peers have ever been online

That (logging) is a use case outside of Prometheus scope, but we'll eventually have infrastructure for that too :) (spoiler: the new gateway will have logstash)

> are currently online

That'd work

**Comment by VictorBjelkholm** [comment]
> That (logging) is a use case outside of Prometheus scope, but we'll eventually have infrastructure for that too :) (spoiler: the new gateway will have logstash)

Hm, I was thinking of something in webrtc-star that would just increment a counter every time a peer joins and then expose that counter via the debug endpoint. Wouldn't that work? Similar as the online counter.

**Comment by lgierth** [comment]
> Hm, I was thinking of something in webrtc-star that would just increment a counter every time a peer joins and then expose that counter via the debug endpoint. Wouldn't that work? Similar as the online counter.

And then you need to persist the counter somewhere :)

**Comment by diasdavid** [comment]
Hey @VictorBjelkholm @lgierth, could you give me what more clear instructions of what you want to get this merged and deployed?

**Comment by lgierth** [comment]
Yes I think this looks good -- but I wonder whether you want to actually count something? The generic stats of the http endpoint are useful, but number of nodes connected, possibly by transport, might also be useful. It's a bit hard to tell what exactly webrtc-star does, there's probably a few more interesting metrics.

**Comment by diasdavid** [comment]
The Signalling Server keeps track of:
- Number of nodes connected to it
- Ids of those nodes

I could also add counters for:
- Number of handshakes
- What are the handshakes happening (src -> dst)

Would this be useful, @lgierth ?

**Comment by lgierth** [comment]
> - Number of nodes connected to it
> - Ids of those nodes
Yeah I've heard that before, but the repo (same for webrtc-direct) still lacks an exact explanation of what is does, and how it ties together with the /libp2p-webrtc-star/ip4/tcp/ws style addresses.

**Comment by diasdavid** [comment]
@VictorBjelkholm is finishing this PR something you would like to do?

**Comment by VictorBjelkholm** [comment]
@diasdavid sure thing!

**Comment by diasdavid** [comment]
@mkg20001 just added metrics! https://github.com/libp2p/js-libp2p-webrtc-star/pull/127

**Comment by mkg20001** [comment]
@diasdavid Can this be closed? #127 is already merged...

**Pull request closed without merging**
