### PR TITLE
fix: replace node buffers with uint8arrays

### LINKED ISSUE #214: Unskip subset of libp2p-interface tests for transport
This module is currently not using the latest `libp2p-interfaces` module, but a tag with a few tests skipped. Context https://github.com/libp2p/js-libp2p-webrtc-star/pull/183#issuecomment-536331736

We should use the latest tests and fix these issues as discussed in #213

### PR DESCRIPTION
**Pull request by achingbrain**
BREAKING CHANGES:

- All deps used by this module now use Uint8Arrays in place of node Buffers

also fixes #214

### CODE REVIEW

**Comment by achingbrain** [comment]
Master of this repo depends on this unmerged branch: https://github.com/libp2p/js-libp2p-interfaces/tree/chore/skip-abort-while-reading-for-webrtc

I think it might need merging before the tests will pass.

**Comment by vasco-santos** [comment]
We have https://github.com/libp2p/js-libp2p-webrtc-star/issues/214 to track the dep issue. There are a couple of tests failling with the interface and we want to tackle them when we iterate on webrtc with distributed signalling.
The easiest solution now is to rebase the interface PR with its master.
I will do it

**Comment by jacobheun** [comment]
I added a PR to aegir to let us just skip this via the cli so we can do it in travis instead of depending on that branch, https://github.com/ipfs/aegir/pull/622. 

I looked into the issue with the tests but will need more time to fix the root cause. The issue with the abort error not being thrown is that SimplePeer is overriding `destroy` on ReadableStream and doing some things that don't conform to standard Stream behavior. We're currently using a fork of SimplePeer anyway, so we should fix it there until we can get rid of ReadableStream altogether.

**Comment by vasco-santos** [comment]
> I added a PR to aegir to let us just skip this via the cli so we can do it in travis instead of depending on that branch, [ipfs/aegir#622](https://github.com/ipfs/aegir/pull/622).
> 
> I looked into the issue with the tests but will need more time to fix the root cause. The issue with the abort error not being thrown is that SimplePeer is overriding `destroy` on ReadableStream and doing some things that don't conform to standard Stream behavior. We're currently using a fork of SimplePeer anyway, so we should fix it there until we can get rid of ReadableStream altogether.

I just updated the interface tag. But, I like your solution more! 👍

**Comment by jacobheun** [comment]
The simple-peer fork needed to switch over to Uint8Arrays, so I went ahead and just fixed the underlying destroy problem. https://github.com/ipfs-shipyard/simple-peer/pull/1

**Pull request merged**
