### PR TITLE
Deploy signalling server

### PR DESCRIPTION
**Pull request by diasdavid**
> Following https://github.com/libp2p/js-libp2p-webrtc-star/issues/38

### CODE REVIEW

**Comment by diasdavid** [comment]
Dokku uses the host header to understand which container to point the request to, and since `multiaddr` doesn't support DNS, we have to dial through IP:PORT which disables us from being able to dial to the signaling.

A possible solution is just to fix the random port that dokku picks and then create a direct proxy to always use that port. @lgierth thoughts? Can you help with that?

**Comment by lgierth** [comment]
Try: `dokku proxy:ports-add $app http:$externalPort:5000`
from http://dokku.viewdocs.io/dokku/advanced-usage/proxy-management/

**Comment by lgierth** [comment]
Note that I updated the IPv4 address of cloud.ipfs.team, it's now 188.166.203.82 -- I had forgotten to use a floating IP.

**Comment by diasdavid** [comment]
Works flawlessly, thank you @lgierth <3

```
» ssh -4 dokku@cloud.ipfs.team proxy:ports webrtc-star-signalling
-----> Port mappings for webrtc-star-signalling
-----> scheme             host port                 container port
http                      20000                     5000
http                      80                        5000
tcp                       20000                     5000
ws                        20000                     5000

```

**Pull request merged**
